services:
    app:
        build:
            context: .
            target: php
            dockerfile: Dockerfile
        container_name: app-RegCurso
        restart: unless-stopped
        tty: true
        working_dir: /var/www/
        volumes:
            - ./:/var/www/
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        depends_on:
            - db
        networks:
            - RegCurso-Net

    server:
        image: nginx:alpine
        container_name: server-RegCurso
        restart: unless-stopped
        ports:
            - "3020:80"
        volumes:
            - ./:/var/www/
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - RegCurso-Net

    db:
        image: mysql:8.0
        container_name: db-RegCurso
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: regcurso
            MYSQL_ROOT_PASSWORD: 94NomaS1V5eA
            MYSQL_USER: admin
            MYSQL_PASSWORD: 94NomaS1V5eA
        volumes:
            - ./dbdata/:/var/lib/mysql/
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - RegCurso-Net

networks:
    RegCurso-Net:
        driver: bridge